Yep 198 multiple form host
Xerataw/Gigz pull request #100
Opened 2023-07-20 14:42 UTC by iittooss

finally, a fully working multi step form for register, host & artist.
33 files ? haha, imagine. Some are renamed or moved files.

2023-07-20 15:09 UTC, iittooss commented
finally, a fully working multi step form for register, host & artist.
33 files ? haha, imagine. Some are renamed or moved files.

2023-07-24 08:36 UTC, filveith requested changes

2023-07-24 08:36 UTC, filveith commented on front/src/api/register.ts
> +export default register;
Same here for the type instead of any

2023-07-24 08:36 UTC, filveith commented on front/src/assets/i18n/en.json
> +  "stepper": {
Maybe register would be more appropriate instead of stepper

2023-07-24 08:36 UTC, filveith commented on front/src/components/Steps/AddressCompleteStep.tsx
> +      <StepTitle label={label} />
Comme discuté, il faudrait déplacer le StepTitle dans le composant parent pour éviter de devoir l'ajouter dans tous les composants enfants. Et comme ça pas besoin de passer le label en props à tous les composants

2023-07-24 08:36 UTC, filveith commented on front/src/components/Steps/NameStep.tsx
> +    </>
label of StepTitle, label of TextInput and placeholder are not translated

2023-07-24 08:36 UTC, filveith commented on front/src/components/Steps/StepperCompleted.tsx
>        </Text>
I think that using the translation directly in each component would be better than passing it as a prop

2023-07-24 08:36 UTC, filveith commented on front/src/components/Steps/Utils/StepperIcons.tsx
> +      {currentStep < 5 && hasSkip === true && (
Don't need to explicity check if hasSkip is true

2023-07-24 08:36 UTC, filveith commented on front/src/configs/steppers/stepperArtistConfig.tsx
> +          : 'La description est trop longue',
Missing translations

2023-07-24 08:36 UTC, filveith commented on front/src/configs/steppers/stepperArtistConfig.tsx
> +        ),
No translation

2023-07-24 08:36 UTC, filveith commented on front/src/configs/steppers/stepperArtistConfig.tsx
> +      };
Same

2023-07-24 08:36 UTC, filveith commented on front/src/configs/steppers/stepperHostConfig.tsx
No translation

2023-07-24 08:36 UTC, filveith commented on front/src/configs/steppers/stepperRegisterConfig.tsx
> +);
No translation

2023-07-24 08:36 UTC, filveith commented on front/src/configs/steppers/stepperRegisterConfig.tsx
> +        };
No translation

2023-07-24 08:36 UTC, filveith commented on front/src/pages/Register/Register.tsx
>            Vous avez déjà un compte ?
No translation

2023-07-24 08:36 UTC, filveith commented on front/src/pages/Register/RegisterArtistProfile.tsx
> +  const numberOfSteps = 7;
Name sould be written in PASCAL_CASE because it is not going to change

2023-07-24 08:40 UTC, ASparton requested changes
Problems noticed when I was testing the feature :
- Skip arrow not visible
- Profile picture step :
  - Title too big
- Logos shifted
- No validation on social media links
- Do we keep this unseen step where you send the request ? We should probably merge it with the validation step

2023-07-24 13:22 UTC, iittooss commented
All translations will be done later, we need to go forward

2023-07-24 15:08 UTC, ASparton approved these changes

2023-07-24 15:09 UTC, filveith approved these changes

2023-07-24 15:09 UTC, merged